// flow-typed signature: d7e6f6b388e49bd13709648ee1106dd7
// flow-typed version: <<STUB>>/relative-date_v^1.1.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relative-date'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relative-date' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relative-date/lib/relative-date' {
  declare module.exports: any;
}

declare module 'relative-date/test/node' {
  declare module.exports: any;
}

declare module 'relative-date/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relative-date/lib/relative-date.js' {
  declare module.exports: $Exports<'relative-date/lib/relative-date'>;
}
declare module 'relative-date/test/node.js' {
  declare module.exports: $Exports<'relative-date/test/node'>;
}
declare module 'relative-date/test/test.js' {
  declare module.exports: $Exports<'relative-date/test/test'>;
}
